name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - beta

env:
  FASTLANE_SKIP_UPDATE_CHECK: true
  FASTLANE_XCODE_LIST_TIMEOUT: 30
  MATCH_KEYCHAIN_NAME: "gh_actions"

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
        env:
          DIFF_BASE: ${{ github.base_ref }}

  test:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      name: "Cache: Pods"
      with:
        path: |
          Pods
          Tools/MaterialDesignIcons.ttf
          Tools/MaterialDesignIcons.json
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock', 'Tools/BuildMaterialDesignIconsFont.sh') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - uses: actions/cache@v2
      name: "Cache: Gems"
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - uses: actions/cache@v2
      name: "Cache: Swift Package Manager"
      with:
        path: ~/Library/Developer/Xcode/DerivedData/HomeAssistant-*/SourcePackages/
        key: ${{ runner.os }}-spm-${{ hashFiles('HomeAssistant.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Install Gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Install Pods
      run: diff Pods/Manifest.lock Podfile.lock >/dev/null || bundle exec pod install --repo-update

    - name: Run tests
      run: bundle exec fastlane ios test

    - uses: codecov/codecov-action@v1
      name: "Upload Code Coverage"

    - uses: actions/upload-artifact@v2
      name: "Upload Test Logs"
      if: ${{ always() }}
      with:
        name: test-logs
        path: |
          ~/Library/Logs/DiagnosticReports
          ~/Library/Developer/Xcode/DerivedData/HomeAssistant-*/Logs/Test
          ~/Library/Logs/scan
